version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - echo "Instalando Amazon.Lambda.Tools globalmente..."
      - dotnet tool install -g Amazon.Lambda.Tools
      - export PATH="$PATH:/root/.dotnet/tools"  # Necesario para usar tools en CodeBuild
      - echo "Creando carpeta de salida..."
      - mkdir -p output
      - echo "Restaurando dependencias..."
      - dotnet restore AWSLambdaEjemplo/AWSLambdaEjemplo.csproj
      - echo "Empaquetando Lambda..."
      - dotnet lambda package --project-location AWSLambdaEjemplo/AWSLambdaEjemplo.csproj --output-package output/function.zip

artifacts:
  files:
    - output/function.zip
